name: Atualizar JSON

on:
  repository_dispatch:
    types: [atualizar-json]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Atualizar JSON
        run: |
          echo '{"status": "atualizado"}' > servo_control.json

      - name: Commit e push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add servo_control.json
          git commit -m "Atualizando JSON automaticamente"
          git push
