name: Atualizar JSON

on:
  workflow_dispatch: # Permite rodar manualmente
  repository_dispatch: # Permite rodar via API externa

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Modificar JSON
        run: |
          echo '{ "valor": "novo_dado" }' > servo_control.json

      - name: Commit e Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add servo_control.json
          git commit -m "Atualizando JSON automaticamente"
          git push
